comments section create, approve and delete ready
fnovellafletcher/mr-admin pull request #1
Opened 2022-10-16 20:56 UTC by fnovellafletcherdev2

2022-10-17 23:30 UTC, roboworski requested changes

2022-10-17 23:30 UTC, roboworski commented on src/components/custom/Crud/Crud.js
> +  console.log(props.customUpdate);
Lanzamos review

2022-10-17 23:30 UTC, roboworski commented on src/components/custom/Crud/Crud.js
> +  console.log(props.customUpdate);
Se te ha colado un console.log

2022-10-17 23:30 UTC, roboworski commented on src/components/custom/Crud/Crud.js
> +  const handleCustomUpdate = (onClick) => async () => {
Este handler es extraño que no venga de la mano de un useCallback

2022-10-17 23:30 UTC, roboworski commented on src/components/custom/Crud/CrudBuilder.js
> +    // console.log(constructorObj);
Código comentado fuera

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/VideoComment.js
> +      // const videoLinks = videos.data
Código comentado fuera

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/VideoComment.js
> +  useEffect(() => {
Si no vas a reusar el loadCrudBuilder, por qué creas una función fuera para luego usarla una sola vez? Personalmente, me sobra useCallback hook.

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/crudBuilder.js
> +    // data: videos.data
Código comentado fuera

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/crudBuilder.js
> +  //   videoToEdit.link = [...(videoToEdit.link || []), cleanData];
- [ ] Eliminar este código comentado

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/crudBuilder.js
> +  //   const info = idSplitter(id);
Código comentado eliminar

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/crudBuilder.js
> +  //   const info = idSplitter(id);
Código comentado eliminar

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/crudBuilder.js
> +  console.log(id);
Se te ha colado un console.log

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/crudBuilder.js
> +  //   {
Código comentado eliminar

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/crudBuilder.js
> +  //   {
Código comentado eliminar

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/crudBuilder.js
> +  //   update,
Código comentado eliminar

2022-10-17 23:30 UTC, roboworski commented on src/pages/VideoComment/crudBuilder.js
> +  // formFieldsFilter,
Código comentado eliminar

2022-10-17 23:30 UTC, roboworski commented on src/services/comment/ApiService.js
> +    //   const customHeader =  {
Código comentado eliminar

2022-10-17 23:30 UTC, roboworski commented on src/services/comment/ApiService.js
> +    //   const customHeader =  {
Código comentado eliminar

2022-10-17 23:30 UTC, roboworski commented on src/services/comment/ApiService.js
> +  //   async updateComment(commentId, formData) {
Código comentado eliminar

2022-10-17 23:32 UTC, fnovellafletcherdev2 commented on src/components/custom/Crud/Crud.js
> +  console.log(props.customUpdate);
No entiendo este comentario aquí

2022-10-17 23:38 UTC, fnovellafletcherdev2 commented on src/components/custom/Crud/Crud.js
> +  console.log(props.customUpdate);
Efectivamente, voy a eliminarlo

2022-10-17 23:40 UTC, fnovellafletcherdev2 commented on src/components/custom/Crud/Crud.js
> +  const handleCustomUpdate = (onClick) => async () => {
Necesitamos en este caso que este handler asincrono se construya con cada render por la funcionalidad que acomete.

2022-10-28 12:16 UTC, roboworski requested changes
Revisa de nuevo los comentarios

2022-10-28 12:17 UTC, roboworski approved these changes

2022-10-28 12:18 UTC, merged